# Generated by Django 5.1.6 on 2025-02-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('valor_total', models.CharField(max_length=50)),
                ('pedido', models.CharField(max_length=50)),
                ('data_pedido', models.DateField(max_length=8)),
            ],
        ),
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.CreateModel(
            name='ItensProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.BinaryField(max_length=7)),
                ('preco_unitario', models.BinaryField(max_length=50)),
                ('produto', models.CharField(max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
