# Generated by Django 5.1.6 on 2025-02-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_pedido_rename_clientes_cliente_itensproduto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensproduto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=12),
        ),
    ]
